spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo01
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: '@N4a1m2.'
    
mybatis:
    mapper-locations: classpath:com/example/demo/dao/mapper/*.xml
    type-aliases-package: com.example.demo.entity
 